- lib/components/emergency_room_list_view.dart
- lib/components/emergency_room_list_view_card.dart
- lib/main.dart
- lib/pages/emergency_room_overview.dart
This pull request adds the serveral widgets to display the emergency rooms.
closes #6 
1. Replace "LandingPage" in `main` with "EmergencyRoomOverview"
2. Run app
> add emergency room list

- lib/main.dart
- lib/pages/emergency_room_overview.dart
- lib/pages/home.dart
- lib/pages/landing.dart
add homepage and make it accessible from landing
closes #14
Testing Instructions
- run app
> add homepage

- lib/components/question_answer_column.dart
- lib/pages/home.dart
- lib/pages/landing.dart
- lib/pages/questionnaire.dart
This pull request adds questionnaire page and navigation to it and also a reusable question column
closes #15
- Navigate Starte->Fragebogen->Ja/Nein (Nein takes 2 seconds)
> Add questionnaire page and navigation to it

- lib/components/emergency_room_list_view.dart
- lib/components/emergency_room_list_view_card.dart
- lib/components/question_answer_column.dart
- lib/components/street_map.dart
- lib/main.dart
- lib/pages/emergency_room_overview.dart
- lib/pages/home.dart
- lib/pages/landing.dart
- lib/pages/questionnaire.dart
- lib/styling/constants.dart
- lib/styling/dark_theme.dart
- lib/styling/light_theme.dart
- lib/styling/streetmap_marker.dart
> Change styling to use styling constants

- lib/l10n/app_de.arb
- lib/l10n/app_en.arb
- lib/main.dart
- lib/pages/home.dart
- lib/pages/landing.dart
- lib/pages/questionnaire.dart
- lib/pages/setting.dart
- lib/pages/setting_language_selection.dart
- lib/services/language_model.dart
In this pull request translation for german and englisch language added addtional now the state for darkmode and slected language is displayed as subtitle
> Translation for German and English

- lib/config/language.dart
- lib/main.dart
- lib/pages/setting_language_selection.dart
- lib/services/language_model.dart
closes #33
- open app an test language changing
> move language constants to a seperate file

- lib/pages/setting.dart
icons now are bigger and veritcally centered
closes #34
> restyle setting page list tiles

- lib/pages/setting_language_selection.dart
closes #37
- go to setting->language/Sprache
> radio list tiles in language selection

- lib/components/question_answer_column.dart
- lib/pages/home.dart
- lib/styling/constants.dart
- lib/styling/dark_theme.dart
- lib/styling/light_theme.dart
closes #40
light theme is now light
- open app
- change to light and dark mode
> update light and dark theme

- ios/Flutter/Debug.xcconfig
- ios/Flutter/Release.xcconfig
- ios/Podfile
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcworkspace/contents.xcworkspacedata
This pull request introduces the minimum iOS version of 12.0.0.
Closes #47
> fix(#47): use flutter run to create the default podfile setup

- lib/components/emergency_room_bottom_sheet.dart
- lib/components/street_map.dart
- lib/pages/street_map_view.dart
- lib/styling/constants.dart
in this Pull Request i added localistaion function on EmergencyRoomListViewCard and a floating-button for localisation on StreetMapViewPage
> fix: localisation in EmergencyRoomListViewCard

- lib/components/emergency_room_list_view_card.dart
- lib/l10n/app_en.arb
> internationalization in emergency_room_list_view_card.dart

- lib/components/emergency_room_bottom_sheet.dart
> feat: removing of deprecated body text

- README.md
> add internationalization to readme

- lib/components/chat_message.dart
- lib/components/emergency_room_bottom_sheet.dart
- lib/components/emergency_room_list_view_card.dart
- lib/components/question_answer_column.dart
- lib/l10n/app_de.arb
- lib/l10n/app_en.arb
- lib/pages/emergency_chat.dart
- lib/pages/landing.dart
- lib/styling/constants.dart
- lib/styling/dark_theme.dart
- lib/styling/light_theme.dart
> add emergency chat room

- ios/Runner/Info.plist
- lib/main.dart
closes #69
only portrait mode for android and ios
> only portrait mode for android and ios

- lib/components/emergency_room_list_view.dart
- lib/components/emergency_room_list_view_card.dart
- lib/components/question_answer_column.dart
- lib/pages/emergency_chat.dart
> feat: remove deprecated keywords

- lib/components/blood_type_select.dart
> fix renderflex issue

- README.md
> Add notice for BrowserStack

- lib/components/content_selection/content_selector.dart
- lib/components/content_selection/list_search.dart
- lib/l10n/app_de.arb
- lib/l10n/app_en.arb
- lib/pages/emergency_pass.dart
> add multiselect for content selector

- lib/components/content_selection/content_selector.dart
- lib/components/content_selection/list_search.dart
- lib/pages/emergency_pass.dart
> add avoidance of empty inputs content selector

- lib/pages/emergency_pass.dart
- lib/styling/constants.dart
- lib/styling/dark_theme.dart
- lib/styling/light_theme.dart
> fix invisible borders with theme update

- lib/styling/light_theme.dart
> fix light theme to show date picker

- lib/components/content_selection/content_selector.dart
- lib/components/content_selection/list_search.dart
- lib/pages/emergency_pass.dart
> refactor content selection

- lib/pages/setting_language_selection.dart
- lib/services/language_model.dart
- lib/services/language_preferences.dart
> fix language model

- lib/components/emergency_room_bottom_sheet.dart
- lib/l10n/app_de.arb
- lib/styling/constants.dart
> fix too long notifyCancel text

- .github/workflows/ci.yaml
- ios/Podfile.lock
- ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
> Build and upload apk to BrowserStack

- lib/pages/settings_page.dart
> change pushReplacement to push

- lib/config/language.dart
- lib/main.dart
- lib/services/language_model.dart
- lib/services/language_preferences.dart
closes #128
We maybe want to consider how and what to save. Currently we are storing the local (Country e.g DE) instead of the language (Language Shortname e.g en). We probably want to save both.
> use device default language

- lib/main.dart
- lib/pages/settings_page.dart
- lib/services/theme_model.dart
- lib/services/theme_preferences.dart
closes #123
doesn't work on android 9, probably not on <10
defaults to light mode
> theme notifier uses os theme

- lib/main.dart
- lib/services/database_handler.dart
- lib/services/patient_persistence.dart
- pubspec.yaml
> change persistence to sql

- .github/workflows/ci.yaml
- apps/tasks/pubspec.yaml
> update flutter version in ci

- apps/tasks/android/gradle/wrapper/gradle-wrapper.properties
> fix: unsupported class file major version 63

- apps/helpwave/lib/pages/emergency_pass_page.dart
- packages/helpwave_localization/lib/src/localization_impl.dart
> add explicit typing on LocalizationExtension

- apps/helpwave/lib/pages/emergency_pass_page.dart
- apps/helpwave/lib/pages/landing_page.dart
- apps/helpwave/lib/pages/settings_page.dart
- apps/helpwave/pubspec.yaml
- packages/helpwave_widget/.gitignore
- packages/helpwave_widget/.metadata
- packages/helpwave_widget/CHANGELOG.md
- packages/helpwave_widget/README.md
- packages/helpwave_widget/analysis_options.yaml
- packages/helpwave_widget/lib/content_selection.dart
- packages/helpwave_widget/lib/dialog.dart
- packages/helpwave_widget/lib/src/content_selection/content_selector.dart
- packages/helpwave_widget/lib/src/content_selection/list_entry.dart
- packages/helpwave_widget/lib/src/content_selection/list_search.dart
- packages/helpwave_widget/lib/src/dialog_impl.dart
- packages/helpwave_widget/pubspec.yaml
> add widget package

- .github/workflows/ci.yaml
- melos.yaml
> update ci for helpwave tasks

- apps/tasks/lib/config/config.dart
- apps/tasks/lib/main.dart
- apps/tasks/lib/pages/login_page.dart
- apps/tasks/lib/pages/register_page.dart
- packages/helpwave_localization/lib/l10n/app_de.arb
- packages/helpwave_localization/lib/l10n/app_en.arb
- packages/helpwave_theme/lib/src/constants.dart
- packages/helpwave_theme/lib/src/dark_theme.dart
- packages/helpwave_theme/lib/src/light_theme.dart
> add login and registration page

- apps/tasks/lib/pages/register_page.dart
> button overlap

- packages/helpwave_widget/lib/src/content_selection/content_selector.dart
- packages/helpwave_widget/lib/src/content_selection/list_search.dart
> ListSearch Builder updated

- apps/helpwave/lib/services/database_handler.dart
- apps/helpwave/lib/services/patient_persistence.dart
> update data base to only use allowed types

- apps/tasks/lib/pages/login_page.dart
- apps/tasks/lib/pages/register_page.dart
- packages/helpwave_widget/lib/src/text_input/password_text_editing_field.dart
- packages/helpwave_widget/lib/text_input.dart
> add password field widget

- apps/tasks/lib/pages/login_page.dart
- apps/tasks/lib/pages/organization_picker_dart.dart
- apps/tasks/lib/pages/register_page.dart
- packages/helpwave_localization/lib/l10n/app_de.arb
- packages/helpwave_localization/lib/l10n/app_en.arb
- packages/helpwave_widget/lib/src/widgets/widgets.dart
- packages/helpwave_widget/lib/widgets.dart
> add organization picker

- packages/helpwave_widget/lib/src/loading/loading_spinner.dart
- packages/helpwave_widget/lib/src/static_progress_indicator/static_progress_indicator.dart
- packages/helpwave_widget/lib/static_progress_indicator.dart
> add Static Progress Indicator

- apps/tasks/lib/components/task_status_pill.dart
- apps/tasks/lib/components/task_status_pill_box.dart
- apps/tasks/lib/util/diagonal_clipper.dart
- packages/helpwave_widget/lib/shapes.dart
- packages/helpwave_widget/lib/src/shapes/circle.dart
> add task status pills

- apps/helpwave/lib/components/chat_message.dart
- apps/helpwave/lib/main.dart
- apps/helpwave/lib/screens/emergency_chat_screen.dart
- apps/helpwave/lib/screens/emergency_pass_screen.dart
- apps/helpwave/lib/screens/emergency_room_overview_screen.dart
- apps/helpwave/lib/screens/home_screen.dart
- apps/helpwave/lib/screens/landing_screen.dart
- apps/helpwave/lib/screens/language_selection_screen.dart
- apps/helpwave/lib/screens/questionnaire_screen.dart
- apps/helpwave/lib/screens/settings_screen.dart
- apps/helpwave/lib/screens/street_map_screen.dart
- apps/tasks/lib/main.dart
- apps/tasks/lib/screens/home_screen.dart
- apps/tasks/lib/screens/login_screen.dart
- apps/tasks/lib/screens/organization_picker_screen.dart
- apps/tasks/lib/screens/organization_screen.dart
- apps/tasks/lib/screens/register_screen.dart
> change naming convention to screen

- apps/tasks/lib/components/task_status_pill_box.dart
> fix backgroundColor to be pillDefault

- apps/tasks/lib/screens/settings_screen.dart
> fix theme not changing

- melos.yaml
> simplify melos run intl usage

- apps/helpwave/lib/main.dart
- apps/helpwave/lib/screens/settings_screen.dart
- apps/tasks/lib/main.dart
- apps/tasks/lib/screens/settings_screen.dart
- packages/helpwave_theme/lib/src/theme_model.dart
> improve theme package

- apps/tasks/lib/components/task_list_tile.dart
- packages/helpwave_widget/lib/src/static_progress_indicator/static_progress_indicator.dart
> Issue/248 TaskListTile 

- apps/tasks/lib/components/navigation_drawer.dart
- apps/tasks/lib/screens/my_tasks_screen.dart
> MyTaskScreen

- apps/tasks/lib/components/task_list_tile.dart
- apps/tasks/lib/screens/my_tasks_screen.dart
- packages/helpwave_localization/lib/l10n/app_de.arb
- packages/helpwave_localization/lib/l10n/app_en.arb
> Add swipe gestures to delete and mark a task as done 

- apps/tasks/lib/components/bed_card.dart
- apps/tasks/lib/components/task_status_pill.dart
- apps/tasks/lib/components/task_status_pill_box.dart
- apps/tasks/lib/main.dart
- apps/tasks/lib/screens/room_overview_screen.dart
- apps/tasks/lib/util/diagonal_clipper.dart
- packages/helpwave_localization/lib/l10n/app_de.arb
- packages/helpwave_localization/lib/l10n/app_en.arb
- packages/helpwave_theme/lib/src/constants.dart
Closes #183 
Strongly depends on #191 as there are so many undefined colors and widget sizes.
> RoomOverviewScreen

- apps/tasks/lib/components/patient_card.dart
- apps/tasks/lib/dataclasses/patient.dart
- apps/tasks/lib/screens/landing_screen.dart
- apps/tasks/lib/screens/my_tasks_screen.dart
- packages/helpwave_localization/lib/l10n/app_de.arb
- packages/helpwave_localization/lib/l10n/app_en.arb
closes #269
Look at the MyTasksScreen
> make patient card from bed card

- apps/tasks/lib/screens/my_tasks_screen.dart
- packages/helpwave_localization/lib/l10n/app_de.arb
- packages/helpwave_localization/lib/l10n/app_en.arb
- packages/helpwave_theme/lib/src/constants.dart
> feat: first draft for dismissible on PatientCard

- README.md
> remove old helpwave app from readme

- .gitignore
- apps/tasks/lib/screens/my_tasks_screen.dart
- packages/helpwave_localization/lib/l10n/app_de.arb
- packages/helpwave_localization/lib/l10n/app_en.arb
- packages/helpwave_theme/lib/src/constants.dart
- packages/helpwave_theme/lib/src/dark_theme.dart
- packages/helpwave_theme/lib/src/light_theme.dart
> update Searchbar theme and implement it on task screen

- apps/tasks/lib/dataclasses/task_template.dart
- apps/tasks/lib/dataclasses/task_template_subtask.dart
> chore: add task template data class

- packages/helpwave_theme/lib/src/constants.dart
- packages/helpwave_theme/lib/src/dark_theme.dart
- packages/helpwave_theme/lib/src/light_theme.dart
- packages/helpwave_widget/lib/src/content_selection/chip_select.dart
> change chip style

- .github/workflows/ci.yaml
- melos.yaml
> ci: remove tasks temporary from ci

- apps/impulse/lib/components/activity_card.dart
- apps/impulse/pubspec.lock
- apps/impulse/pubspec.yaml
> feat: first draft for ActivityCard

- apps/impulse/lib/components/number_input.dart
> feat: first draft for NumberInput-field

- apps/impulse/assets/svg/medal.svg
- apps/impulse/lib/components/medal.dart
- apps/impulse/lib/components/medal_carusel.dart
- apps/impulse/lib/main.dart
- apps/impulse/pubspec.lock
- apps/impulse/pubspec.yaml
> add Carousel

- apps/impulse/lib/components/progressbar.dart
- apps/impulse/lib/components/timer_component.dart
- apps/impulse/lib/main.dart
- apps/impulse/lib/theming/colors.dart
- apps/impulse/pubspec.lock
- apps/tasks/pubspec.lock
> add progressbar

- apps/impulse/lib/dataclasses/reward.dart
> feat: add reward class

- apps/impulse/lib/components/activity_card.dart
- apps/impulse/lib/components/xp_label.dart
- apps/impulse/lib/main.dart
- apps/impulse/lib/screens/HomeScreen.dart
- apps/impulse/lib/theming/colors.dart
> add home screen

- apps/impulse/android/app/build.gradle
- apps/impulse/lib/components/activity_card.dart
- apps/impulse/lib/components/challange_menu_card.dart
- apps/impulse/lib/components/number_input.dart
- apps/impulse/lib/components/qr_scanner_wrapper.dart
- apps/impulse/lib/components/verification_method.dart
- apps/impulse/lib/dataclasses/challange.dart
- apps/impulse/lib/main.dart
- apps/impulse/lib/screens/challange_screen.dart
- apps/impulse/lib/screens/home_screen.dart
- apps/impulse/pubspec.lock
- apps/impulse/pubspec.yaml
> add challange_screen

- apps/impulse/lib/components/activity_card.dart
- apps/impulse/lib/screens/home_screen.dart
- apps/impulse/lib/theming/colors.dart
> feat: add color

- apps/impulse/lib/components/challange_menu_card.dart
- apps/impulse/lib/components/medal_carusel.dart
- apps/impulse/lib/components/profile_form.dart
- apps/impulse/lib/components/verification_method.dart
- apps/impulse/lib/dataclasses/challange.dart
- apps/impulse/lib/dataclasses/team.dart
- apps/impulse/lib/dataclasses/user.dart
- apps/impulse/lib/dataclasses/verifier.dart
- apps/impulse/lib/main.dart
- apps/impulse/lib/screens/challange_screen.dart
- apps/impulse/lib/screens/home_screen.dart
- apps/impulse/lib/services/grpc_client_svc.dart
- apps/impulse/lib/services/impulse_service.dart
- apps/impulse/lib/util/level.dart
- apps/impulse/pubspec.lock
- apps/impulse/pubspec.yaml
> feat: add grpc for challenge fetching

- apps/impulse/lib/components/background_gradient.dart
- apps/impulse/lib/main.dart
- apps/impulse/lib/screens/boarding_screen.dart
- apps/impulse/lib/screens/challange_screen.dart
- apps/impulse/lib/screens/home_screen.dart
- apps/impulse/pubspec.lock
- apps/impulse/pubspec.yaml
- packages/helpwave_service/lib/src/introduction_model.dart
- packages/helpwave_service/lib/src/introduction_preference.dart
> show introduction only once

- apps/tasks/lib/screens/main_screen_subscreens/create_screen.dart
> move floating action button to its own component

- apps/tasks/lib/screens/settings_screen.dart
- packages/helpwave_localization/lib/localization.dart
- packages/helpwave_localization/lib/src/config/language.dart
- packages/helpwave_localization/lib/src/language_model.dart
- packages/helpwave_localization/lib/src/language_with_translation.dart
> update language service and use it in tasks app

- .github/workflows/ci.yaml
- melos.yaml
Re-enable helpwave tasks app and running builds in parallel
> ci: running builds in parallel

- apps/tasks/lib/components/user_header.dart
- apps/tasks/lib/screens/main_screen_subscreens/my_tasks_screen.dart
- apps/tasks/lib/screens/main_screen_subscreens/patient_screen.dart
> update UserHeader and use it as AppBar

- packages/helpwave_localization/README.md
- packages/helpwave_localization/pubspec.yaml
- packages/helpwave_service/README.md
- packages/helpwave_service/pubspec.yaml
- packages/helpwave_theme/README.md
- packages/helpwave_widget/README.md
- packages/helpwave_widget/pubspec.yaml
> add documentation to packages

- apps/tasks/lib/components/patient_bottom_sheet.dart
> add PatientBottomSheet documentation

- packages/helpwave_widget/lib/src/text_input/clickable_text_edit.dart
- packages/helpwave_widget/lib/text_input.dart
> add ClickableTextEdit

- apps/tasks/lib/components/patient_status_chip_select.dart
- apps/tasks/lib/components/task_card.dart
- apps/tasks/lib/controllers/my_tasks_controller.dart
- apps/tasks/lib/controllers/patients_controller.dart
- apps/tasks/lib/dataclasses/patient.dart
- apps/tasks/lib/dataclasses/task.dart
- apps/tasks/lib/screens/main_screen_subscreens/my_tasks_screen.dart
- apps/tasks/lib/screens/main_screen_subscreens/patient_screen.dart
- apps/tasks/lib/services/patient_svc.dart
- apps/tasks/lib/util/search_helpers.dart
- packages/helpwave_widget/lib/loading.dart
- packages/helpwave_widget/lib/src/loading/loading_and_error_widget.dart
- packages/helpwave_widget/lib/src/loading/loading_future_builder.dart
> add basic controllers for tasks

- apps/tasks/lib/components/assignee_select.dart
- apps/tasks/lib/components/task_bottom_sheet.dart
- packages/helpwave_localization/lib/l10n/app_de.arb
- packages/helpwave_localization/lib/l10n/app_en.arb
> assignee select

- apps/impulse/pubspec.lock
- apps/tasks/lib/components/assignee_select.dart
- apps/tasks/lib/components/patient_bottom_sheet.dart
- apps/tasks/lib/components/subtask_list.dart
- apps/tasks/lib/components/task_bottom_sheet.dart
- apps/tasks/lib/components/visibility_select.dart
- apps/tasks/lib/controllers/task_controller.dart
- apps/tasks/lib/controllers/user_controller.dart
- apps/tasks/lib/dataclasses/patient.dart
- apps/tasks/lib/dataclasses/task.dart
- apps/tasks/lib/dataclasses/user.dart
- apps/tasks/lib/services/grpc_client_svc.dart
- apps/tasks/lib/services/organization_svc.dart
- apps/tasks/lib/services/task_svc.dart
- apps/tasks/lib/services/user_service.dart
- apps/tasks/lib/util/task_status_mapping.dart
- packages/helpwave_widget/lib/src/bottom_sheets/bottom_sheet_base.dart
- packages/helpwave_widget/lib/src/loading/loading_and_error_widget.dart
- packages/helpwave_widget/lib/src/text_input/clickable_text_edit.dart
> add TaskController

- apps/tasks/lib/controllers/my_tasks_controller.dart
- apps/tasks/lib/dataclasses/patient.dart
- apps/tasks/lib/services/patient_svc.dart
> loading tasks from backend

- apps/tasks/lib/components/assignee_select.dart
- apps/tasks/lib/components/task_bottom_sheet.dart
- apps/tasks/lib/controllers/assignee_select_controller.dart
- apps/tasks/lib/controllers/task_controller.dart
- apps/tasks/lib/main.dart
- apps/tasks/lib/screens/main_screen.dart
- apps/tasks/lib/screens/settings_screen.dart
- apps/tasks/lib/screens/ward_select_screen.dart
- apps/tasks/lib/services/current_ward_svc.dart
- apps/tasks/lib/services/task_svc.dart
- apps/tasks/pubspec.lock
- apps/tasks/pubspec.yaml
> add backend connection and updates to assignee_select

- apps/tasks/lib/services/user_session_service.dart
- packages/helpwave_service/lib/src/auth/authentication_service.dart
> feat: update logout and unsuccessful login behavior

- apps/tasks/lib/controllers/assignee_select_controller.dart
- apps/tasks/pubspec.yaml
- packages/helpwave_service/lib/src/auth/authentication_service.dart
- packages/helpwave_service/pubspec.yaml
> feat: first draft for logger

- apps/tasks/lib/controllers/assignee_select_controller.dart
This is Pull Request for fixing already merged pipeline issues
> fix: unused variable

- apps/tasks/lib/components/task_bottom_sheet.dart
- apps/tasks/lib/controllers/task_controller.dart
- apps/tasks/lib/controllers/user_controller.dart
- apps/tasks/lib/dataclasses/task.dart
- apps/tasks/lib/services/grpc_client_svc.dart
- apps/tasks/lib/services/task_svc.dart
- apps/tasks/lib/services/user_service.dart
- packages/helpwave_widget/lib/loading.dart
- packages/helpwave_widget/lib/src/loading/loading_and_error_widget.dart
- packages/helpwave_widget/lib/src/loading/pulsing_container.dart
update task bottom sheet to load all information and update loading widget
closes #449
> update layout in bottom sheets 

- apps/tasks/lib/components/user_bottom_sheet.dart
> feat: replace hardcode  username in user_bottom_sheet.dart

- apps/tasks/lib/components/patient_bottom_sheet.dart
- apps/tasks/lib/screens/main_screen_subscreens/patient_screen.dart
> feat: refetch on patient updates

- apps/tasks/lib/components/subtask_list.dart
- apps/tasks/lib/config/config.dart
- packages/helpwave_localization/lib/l10n/app_de.arb
- packages/helpwave_localization/lib/l10n/app_en.arb
> make subtask name editable

- apps/tasks/lib/components/patient_bottom_sheet.dart
- apps/tasks/lib/components/patient_card.dart
- apps/tasks/lib/components/subtask_list.dart
- apps/tasks/lib/components/task_bottom_sheet.dart
- apps/tasks/lib/components/task_card.dart
- apps/tasks/lib/components/task_expansion_tile.dart
- apps/tasks/lib/config/config.dart
- apps/tasks/lib/debug/theme_visualizer.dart
- apps/tasks/lib/screens/main_screen.dart
- apps/tasks/lib/screens/main_screen_subscreens/patient_screen.dart
- packages/helpwave_theme/lib/src/constants.dart
- packages/helpwave_theme/lib/src/dark_theme.dart
- packages/helpwave_theme/lib/src/light_theme.dart
- packages/helpwave_widget/lib/src/lists/add_list.dart
- packages/helpwave_widget/lib/src/loading/loading_spinner.dart
- packages/helpwave_widget/lib/src/text_input/clickable_text_edit.dart
closes #462
closes #280
closes #191
> fix themes

- apps/tasks/lib/components/user_bottom_sheet.dart
- apps/tasks/lib/components/user_header.dart
> feat: update consumer usage

- apps/tasks/lib/components/patient_bottom_sheet.dart
- apps/tasks/lib/components/task_bottom_sheet.dart
- apps/tasks/lib/components/task_expansion_tile.dart
- apps/tasks/lib/components/user_header.dart
- apps/tasks/lib/components/visibility_select.dart
- apps/tasks/lib/screens/main_screen.dart
- apps/tasks/lib/screens/main_screen_subscreens/my_tasks_screen.dart
- apps/tasks/lib/screens/main_screen_subscreens/patient_screen.dart
- packages/helpwave_theme/lib/src/theme.dart
- packages/helpwave_widget/lib/src/bottom_sheets/bottom_sheet_base.dart
> expandable bottom sheet

- apps/impulse/pubspec.lock
- apps/tasks/lib/components/assignee_select.dart
- apps/tasks/lib/components/task_bottom_sheet.dart
- apps/tasks/lib/components/task_expansion_tile.dart
- apps/tasks/lib/config/config.dart
- apps/tasks/lib/controllers/my_tasks_controller.dart
- apps/tasks/lib/controllers/task_controller.dart
- apps/tasks/lib/services/task_svc.dart
- apps/tasks/pubspec.lock
- packages/helpwave_util/.gitignore
- packages/helpwave_util/.metadata
- packages/helpwave_util/CHANGELOG.md
- packages/helpwave_util/README.md
- packages/helpwave_util/analysis_options.yaml
- packages/helpwave_util/lib/src/time/timed_value_updater.dart
- packages/helpwave_util/lib/time.dart
- packages/helpwave_util/pubspec.yaml
- packages/helpwave_widget/lib/src/text_input/clickable_text_edit.dart
- packages/helpwave_widget/lib/src/text_input/text_form_field_with_timer.dart
- packages/helpwave_widget/lib/text_input.dart
> add backend connection to my tasks screen

- README.md
> add impulse app to README.md

- apps/tasks/lib/components/user_header.dart
> user header shows only organization shortname

- apps/tasks/lib/screens/main_screen.dart
> feat: make floating button opaque

- apps/tasks/lib/screens/settings_screen.dart
- packages/helpwave_localization/lib/l10n/app_de.arb
- packages/helpwave_localization/lib/l10n/app_en.arb
> make tri-state theme select

- apps/tasks/lib/screens/main_screen.dart
- packages/helpwave_localization/lib/l10n/app_de.arb
- packages/helpwave_localization/lib/l10n/app_en.arb
- packages/helpwave_widget/lib/animation.dart
- packages/helpwave_widget/lib/src/animation/pop_in_and_out_animator.dart
> change FAB animation an label

- apps/tasks/lib/components/subtask_list.dart
- packages/helpwave_widget/lib/src/text_input/clickable_text_edit.dart
- packages/helpwave_widget/lib/src/text_input/text_form_field_with_timer.dart
> add edit icon to screens

- apps/tasks/lib/services/grpc_client_svc.dart
- apps/tasks/lib/services/patient_svc.dart
> fix: wrong organisation

- apps/tasks/lib/components/patient_bottom_sheet.dart
- apps/tasks/lib/controllers/ward_patients_controller.dart
> feat: disable discharge button if patient already discharged

- packages/helpwave_widget/lib/src/bottom_sheets/bottom_sheet_base.dart
This adds the ability to close a modal by clicking the background.
Also setState got replaced with ValueListenableBuilder so that the child does not need to get rebuild every time the offset changes.
Closes issue #498 
1. Go to the tasks app home page
2. Click on the navigationbar option 'Neu'
3. Click on either 'Task' or 'Patient'
4. Click on the semi-transparent background
Additional notes:
- replaced Scaffold with Material widget since the AppBar of the Scaffold was not used and so the widgets have the same effect with the exception, that Material does not take up the whole screen.
> make modals closable by clicking the background
